'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { signIn } from 'next-auth/react'
import { useRegisterUserMutation } from '@/lib/generated'

export default function RegisterForm() {
  const router = useRouter()
  
  // Form fields state
  const [name, setName] = useState('')
  const [username, setUsername] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  
  // Custom local error UI tracking
  const [validationError, setValidationError] = useState<string | null>(null)

  // 🤖 Trigger your autogenerated GraphQL Mutation hook
  const { mutate: registerUser, isPending, error: graphQLError } = useRegisterUserMutation({
    onSuccess: async () => {
      // 🚀 Auto-login the user into NextAuth immediately after a successful signup
      const result = await signIn('credentials', {
        redirect: false,
        email,
        password,
      })

      if (result?.error) {
        // If auto-login fails, send them to the default login page instead
        router.push('/api/auth/signin')
      } else {
        // Success! Send them to their profile dashboard page
        router.push('/profile')
        router.refresh()
      }
    },
    onError: (err) => {
      setValidationError(err.message || 'Something went wrong during registration.')
    }
  })

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    setValidationError(null)

    // Quick client-side check for password security
    if (password.length < 6) {
      setValidationError('Password must be at least 6 characters long.')
      return
    }

    // Fire the GraphQL network call with user variables
    registerUser({ email, username, name, password })
  }

  return (
    <div className="w-full max-w-md p-8 space-y-6 bg-white border border-gray-150 rounded-xl shadow-sm">
      <div className="text-center">
        <h1 className="text-2xl font-bold tracking-tight text-gray-950">Create an Account</h1>
        <p className="mt-2 text-sm text-gray-500">
          Sign up to get started with GraphQL & NextAuth
        </p>
      </div>

      {/* ⚠️ Alert Banner Displaying Error Messages */}
      {(validationError || graphQLError) && (
        <div className="p-3 text-sm text-red-600 bg-red-50 border border-red-150 rounded-md">
          {validationError || graphQLError?.message}
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label className="block text-xs font-semibold text-gray-700 uppercase tracking-wider mb-1">
            Full Name
          </label>
          <input
            type="text"
            required
            placeholder="Alex Carter"
            value={name}
            onChange={(e) => setName(e.target.value)}
            className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm shadow-sm focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 transition"
          />
        </div>

        <div>
          <label className="block text-xs font-semibold text-gray-700 uppercase tracking-wider mb-1">
            Username
          </label>
          <input
            type="text"
            required
            placeholder="alex_carter"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm shadow-sm focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 transition"
          />
        </div>

        <div>
          <label className="block text-xs font-semibold text-gray-700 uppercase tracking-wider mb-1">
            Email Address
          </label>
          <input
            type="email"
            required
            placeholder="alex@example.com"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm shadow-sm focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 transition"
          />
        </div>

        <div>
          <label className="block text-xs font-semibold text-gray-700 uppercase tracking-wider mb-1">
            Password
          </label>
          <input
            type="password"
            required
            placeholder="••••••••"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm shadow-sm focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 transition"
          />
        </div>

        <button
          type="submit"
          disabled={isPending}
          className="w-full px-4 py-2.5 text-sm font-medium text-white bg-emerald-600 rounded-md hover:bg-emerald-700 focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:ring-offset-2 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors duration-200"
        >
          {isPending ? 'Registering Account...' : 'Create Account'}
        </button>
      </form>

      <div className="relative flex py-2 items-center text-xs text-gray-400 uppercase tracking-wider">
        <div className="flex-grow border-t border-gray-200"></div>
        <span className="flex-shrink mx-4">Or sign in with</span>
        <div className="flex-grow border-t border-gray-200"></div>
      </div>

      {/* 🔵 Instant Social Google OAuth Redirect */}
      <button
        onClick={() => signIn('google', { callbackUrl: '/profile' })}
        type="button"
        className="w-full flex justify-center items-center gap-2 px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 shadow-sm transition"
      >
        <svg className="w-4 h-4" viewBox="0 0 24 24">
          <path
            fill="#EA4335"
            d="M12.24 10.285V14.4h6.887c-.648 2.41-2.519 4.114-5.136 4.114A5.79 5.79 0 0 1 8.2 12.725a5.79 5.79 0 0 1 5.79-5.79c2.51 0 4.385 1.054 5.4 2.018l3.232-3.232C20.653 3.733 17.65 2 13.99 2 7.92 2 3 6.92 3 12.99s4.92 10.99 10.99 10.99c6.33 0 10.51-4.453 10.51-10.7 0-.724-.065-1.267-.2-1.995H12.24Z"
          />
        </svg>
        Continue with Google
      </button>
    </div>
  )
}
